on:
  pull_request:
    branches: [master]

jobs:
  angular-test-coverage:
    runs-on: ubuntu-latest
    name: test coverage injector
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies with yarn
        run: yarn install

      - name: Istanbul Reporter
        run: npm run coverage

      - name: Coverage report
        uses: ./
        id: report
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/coverage-summary.json
          title: PullRequest Test Coverage
